/**
 * Admin Dashboard
 * 
 * This admin dashboard supports both demo mode and Supabase integration.
 * In demo mode, it uses sample data for demonstration purposes.
 * In production, it connects to Supabase for real data management.
 */

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { toast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { useDocuments } from '@/hooks/useDocuments';
import { BackButton } from '@/components/BackButton';
import {
  Shield, Upload, FileText, Trash2, Eye, Download, Users, BarChart3,
  Edit, LogOut, Plus, BookOpen, FileCheck, TrendingUp, Calendar, AlertCircle
} from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

const DEMO_FILES = [
  { id: '1', title: 'Group 1 Syllabus 2024', description: 'Complete syllabus for TNPSC Group 1', category: 'Syllabus', subcategory: 'Group 1', file_name: 'group1-syllabus.pdf', file_path: '/demo/group1-syllabus.pdf', download_count: 245, created_at: '2024-01-15', file_size: 2500000 },
  { id: '2', title: '10th Standard Tamil Book', description: 'Tamil textbook for 10th standard', category: 'Books', subcategory: '10th Standard', file_name: 'tamil-10th.pdf', file_path: '/demo/tamil-10th.pdf', download_count: 189, created_at: '2024-01-20', file_size: 15000000 },
  { id: '3', title: 'Group 2 Previous Paper 2023', description: 'Previous year question paper', category: 'Previous Papers', subcategory: 'Group 2', file_name: 'group2-2023.pdf', file_path: '/demo/group2-2023.pdf', download_count: 312, created_at: '2024-02-01', file_size: 1800000 },
  { id: '4', title: 'General Studies Notes', description: 'Comprehensive GS notes', category: 'Notes', subcategory: 'General', file_name: 'gs-notes.pdf', file_path: '/demo/gs-notes.pdf', download_count: 156, created_at: '2024-02-10', file_size: 5200000 },
  { id: '5', title: 'Group 4 Syllabus 2024', description: 'Updated syllabus for Group 4', category: 'Syllabus', subcategory: 'Group 4', file_name: 'group4-syllabus.pdf', file_path: '/demo/group4-syllabus.pdf', download_count: 423, created_at: '2024-02-15', file_size: 1200000 },
];

const DEMO_STATS = { totalVisitors: 12458, totalDownloads: 1423, syllabusDownloads: 668, booksDownloads: 287, papersDownloads: 312, notesDownloads: 156 };

interface FileItem { id: string; title: string; description?: string; category: string; subcategory?: string; file_name: string; file_path: string; download_count: number; created_at: string; file_size?: number; }

const Admin = () => {
  const navigate = useNavigate();
  const { user, signOut, isDemoMode } = useAuth();
  const { documents, uploadDocument, deleteDocument, getPublicUrl, refetch } = useDocuments();
  const [files, setFiles] = useState<FileItem[]>([]);
  const [stats, setStats] = useState(DEMO_STATS);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [uploadForm, setUploadForm] = useState({ title: '', description: '', category: '', subcategory: '' });
  const [isUploading, setIsUploading] = useState(false);
  const [editFile, setEditFile] = useState<FileItem | null>(null);
  const [editForm, setEditForm] = useState({ title: '', description: '' });
  const [deleteFile, setDeleteFile] = useState<FileItem | null>(null);
  const [filterCategory, setFilterCategory] = useState('all');
  const categories = ['Syllabus', 'Books', 'Previous Papers', 'Notes'];
  const subcategories: Record<string, string[]> = { 'Syllabus': ['Group 1', 'Group 2', 'Group 4'], 'Books': ['6th Standard', '7th Standard', '8th Standard', '9th Standard', '10th Standard', '11th Standard', '12th Standard'], 'Previous Papers': ['Group 1', 'Group 2', 'Group 4'], 'Notes': ['Tamil', 'General Studies', 'Maths', 'Science'] };

  useEffect(() => {
    if (isDemoMode) { setFiles(DEMO_FILES); setStats(DEMO_STATS); }
    else if (documents) {
      setFiles(documents.map(doc => ({ id: doc.id, title: doc.title, description: doc.description || '', category: doc.category, subcategory: doc.subcategory || '', file_name: doc.file_name, file_path: doc.file_path, download_count: doc.download_count || 0, created_at: doc.created_at, file_size: doc.file_size || 0 })));
      const totalDownloads = documents.reduce((sum, doc) => sum + (doc.download_count || 0), 0);
      setStats({ totalVisitors: 12458, totalDownloads, syllabusDownloads: documents.filter(d => d.category === 'Syllabus').reduce((sum, d) => sum + (d.download_count || 0), 0), booksDownloads: documents.filter(d => d.category === 'Books').reduce((sum, d) => sum + (d.download_count || 0), 0), papersDownloads: documents.filter(d => d.category === 'Previous Papers').reduce((sum, d) => sum + (d.download_count || 0), 0), notesDownloads: documents.filter(d => d.category === 'Notes').reduce((sum, d) => sum + (d.download_count || 0), 0) });
    }
  }, [isDemoMode, documents]);

  const handleUpload = async (e: React.FormEvent) => { e.preventDefault(); if (!selectedFile || !uploadForm.title || !uploadForm.category) { toast({ title: "Error", description: "Please fill all required fields", variant: "destructive" }); return; } setIsUploading(true); if (isDemoMode) { setFiles(prev => [{ id: Date.now().toString(), title: uploadForm.title, description: uploadForm.description, category: uploadForm.category, subcategory: uploadForm.subcategory, file_name: selectedFile.name, file_path: `/demo/${selectedFile.name}`, download_count: 0, created_at: new Date().toISOString(), file_size: selectedFile.size }, ...prev]); toast({ title: "Success", description: "File uploaded (Demo Mode)" }); } else { try { await uploadDocument(selectedFile, uploadForm.title, uploadForm.description, uploadForm.category, uploadForm.subcategory); await refetch(); toast({ title: "Success", description: "File uploaded" }); } catch { toast({ title: "Error", description: "Failed to upload", variant: "destructive" }); } } setIsUploading(false); setSelectedFile(null); setUploadForm({ title: '', description: '', category: '', subcategory: '' }); };
  const handleDelete = async () => { if (!deleteFile) return; if (isDemoMode) { setFiles(prev => prev.filter(f => f.id !== deleteFile.id)); toast({ title: "Deleted", description: "File deleted (Demo Mode)" }); } else { try { await deleteDocument(deleteFile as any); await refetch(); toast({ title: "Deleted", description: "File deleted" }); } catch { toast({ title: "Error", description: "Failed to delete", variant: "destructive" }); } } setDeleteFile(null); };
  const handleEdit = () => { if (!editFile) return; if (isDemoMode) { setFiles(prev => prev.map(f => f.id === editFile.id ? { ...f, title: editForm.title, description: editForm.description } : f)); toast({ title: "Updated", description: "File updated (Demo Mode)" }); } else { toast({ title: "Updated", description: "File updated" }); } setEditFile(null); };
  const handleView = (file: FileItem) => { if (isDemoMode) { toast({ title: "Demo Mode", description: "File viewing simulated" }); } else { window.open(getPublicUrl(file.file_path), '_blank'); } };
  const handleLogout = async () => { await signOut(); navigate('/admin-login'); };
  const formatFileSize = (bytes?: number) => { if (!bytes) return 'N/A'; if (bytes < 1024) return bytes + ' B'; if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'; return (bytes / (1024 * 1024)).toFixed(1) + ' MB'; };
  const formatDate = (dateStr: string) => new Date(dateStr).toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' });
  const filteredFiles = filterCategory === 'all' ? files : files.filter(f => f.category === filterCategory);
  const topDownloads = [...files].sort((a, b) => b.download_count - a.download_count).slice(0, 5);

  return (
    <div className="min-h-screen bg-gradient-soft">
      <div className="bg-card border-b border-border sticky top-0 z-10"><div className="container mx-auto px-4 py-4"><div className="flex items-center justify-between"><div className="flex items-center gap-4"><BackButton /><div className="flex items-center gap-3"><div className="w-10 h-10 bg-gradient-to-br from-red-500 to-orange-500 rounded-full flex items-center justify-center"><Shield className="h-5 w-5 text-white" /></div><div><h1 className="font-bold text-lg">Admin Dashboard</h1><p className="text-xs text-muted-foreground">{isDemoMode ? 'Demo Mode' : user?.email}</p></div></div></div><div className="flex items-center gap-2">{isDemoMode && <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">Demo Mode</Badge>}<Button variant="outline" size="sm" onClick={handleLogout}><LogOut className="h-4 w-4 mr-2" />Logout</Button></div></div></div></div>
      <div className="container mx-auto px-4 py-6">
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-6">
          <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-blue-100 rounded-lg"><Users className="h-5 w-5 text-blue-600" /></div><div><p className="text-xs text-muted-foreground">Visitors</p><p className="text-xl font-bold">{stats.totalVisitors.toLocaleString()}</p></div></div></Card>
          <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-green-100 rounded-lg"><Download className="h-5 w-5 text-green-600" /></div><div><p className="text-xs text-muted-foreground">Downloads</p><p className="text-xl font-bold">{stats.totalDownloads}</p></div></div></Card>
          <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-purple-100 rounded-lg"><FileCheck className="h-5 w-5 text-purple-600" /></div><div><p className="text-xs text-muted-foreground">Syllabus</p><p className="text-xl font-bold">{stats.syllabusDownloads}</p></div></div></Card>
          <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-orange-100 rounded-lg"><BookOpen className="h-5 w-5 text-orange-600" /></div><div><p className="text-xs text-muted-foreground">Books</p><p className="text-xl font-bold">{stats.booksDownloads}</p></div></div></Card>
          <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-red-100 rounded-lg"><FileText className="h-5 w-5 text-red-600" /></div><div><p className="text-xs text-muted-foreground">Papers</p><p className="text-xl font-bold">{stats.papersDownloads}</p></div></div></Card>
          <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-teal-100 rounded-lg"><TrendingUp className="h-5 w-5 text-teal-600" /></div><div><p className="text-xs text-muted-foreground">Notes</p><p className="text-xl font-bold">{stats.notesDownloads}</p></div></div></Card>
        </div>
        <Tabs defaultValue="files" className="space-y-4">
          <TabsList className="grid w-full grid-cols-3 lg:w-auto lg:inline-grid"><TabsTrigger value="files" className="gap-2"><FileText className="h-4 w-4" /><span className="hidden sm:inline">Manage Files</span></TabsTrigger><TabsTrigger value="upload" className="gap-2"><Upload className="h-4 w-4" /><span className="hidden sm:inline">Upload New</span></TabsTrigger><TabsTrigger value="analytics" className="gap-2"><BarChart3 className="h-4 w-4" /><span className="hidden sm:inline">Analytics</span></TabsTrigger></TabsList>
          <TabsContent value="files"><Card className="p-4 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6"><h2 className="text-lg font-semibold">All Files ({files.length})</h2><Select value={filterCategory} onValueChange={setFilterCategory}><SelectTrigger className="w-full sm:w-48"><SelectValue placeholder="Filter by category" /></SelectTrigger><SelectContent><SelectItem value="all">All Categories</SelectItem>{categories.map(cat => <SelectItem key={cat} value={cat}>{cat}</SelectItem>)}</SelectContent></Select></div>{filteredFiles.length === 0 ? <div className="text-center py-12"><AlertCircle className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><p className="text-muted-foreground">No files found</p></div> : <div className="space-y-3">{filteredFiles.map(file => <div key={file.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 bg-muted/50 rounded-lg gap-4"><div className="flex items-start gap-3 flex-1 min-w-0"><div className="p-2 bg-primary/10 rounded-lg shrink-0"><FileText className="h-5 w-5 text-primary" /></div><div className="min-w-0 flex-1"><h3 className="font-medium truncate">{file.title}</h3><p className="text-sm text-muted-foreground truncate">{file.description}</p><div className="flex flex-wrap gap-2 mt-2"><Badge variant="secondary">{file.category}</Badge>{file.subcategory && <Badge variant="outline">{file.subcategory}</Badge>}<span className="text-xs text-muted-foreground flex items-center gap-1"><Download className="h-3 w-3" /> {file.download_count}</span><span className="text-xs text-muted-foreground flex items-center gap-1"><Calendar className="h-3 w-3" /> {formatDate(file.created_at)}</span></div></div></div><div className="flex items-center gap-2 shrink-0"><Button size="sm" variant="outline" onClick={() => handleView(file)}><Eye className="h-4 w-4" /></Button><Button size="sm" variant="outline" onClick={() => { setEditFile(file); setEditForm({ title: file.title, description: file.description || '' }); }}><Edit className="h-4 w-4" /></Button><Button size="sm" variant="destructive" onClick={() => setDeleteFile(file)}><Trash2 className="h-4 w-4" /></Button></div></div>)}</div>}</Card></TabsContent>
          <TabsContent value="upload"><Card className="p-4 sm:p-6"><h2 className="text-lg font-semibold mb-6">Upload New File</h2><form onSubmit={handleUpload} className="space-y-4 max-w-xl"><div className="space-y-2"><Label htmlFor="title">Title *</Label><Input id="title" value={uploadForm.title} onChange={(e) => setUploadForm({ ...uploadForm, title: e.target.value })} placeholder="Enter file title" required /></div><div className="space-y-2"><Label htmlFor="description">Description</Label><Input id="description" value={uploadForm.description} onChange={(e) => setUploadForm({ ...uploadForm, description: e.target.value })} placeholder="Enter file description" /></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-2"><Label>Category *</Label><Select value={uploadForm.category} onValueChange={(v) => setUploadForm({ ...uploadForm, category: v, subcategory: '' })}><SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger><SelectContent>{categories.map(cat => <SelectItem key={cat} value={cat}>{cat}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Subcategory</Label><Select value={uploadForm.subcategory} onValueChange={(v) => setUploadForm({ ...uploadForm, subcategory: v })} disabled={!uploadForm.category}><SelectTrigger><SelectValue placeholder="Select subcategory" /></SelectTrigger><SelectContent>{uploadForm.category && subcategories[uploadForm.category]?.map(sub => <SelectItem key={sub} value={sub}>{sub}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-2"><Label htmlFor="file">File *</Label><div className="border-2 border-dashed border-muted-foreground/25 rounded-lg p-6 text-center"><input id="file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png" onChange={(e) => setSelectedFile(e.target.files?.[0] || null)} className="hidden" /><label htmlFor="file" className="cursor-pointer"><Upload className="h-8 w-8 mx-auto text-muted-foreground mb-2" />{selectedFile ? <p className="text-sm font-medium">{selectedFile.name} ({formatFileSize(selectedFile.size)})</p> : <p className="text-sm text-muted-foreground">Click to select a file</p>}</label></div></div><Button type="submit" disabled={isUploading} className="w-full sm:w-auto">{isUploading ? 'Uploading...' : <><Plus className="h-4 w-4 mr-2" />Upload File</>}</Button></form></Card></TabsContent>
          <TabsContent value="analytics"><div className="grid gap-6 md:grid-cols-2"><Card className="p-4 sm:p-6"><h2 className="text-lg font-semibold mb-4">Downloads by Category</h2><div className="space-y-4">{[{ name: 'Syllabus', count: stats.syllabusDownloads, color: 'bg-purple-500' }, { name: 'Books', count: stats.booksDownloads, color: 'bg-orange-500' }, { name: 'Previous Papers', count: stats.papersDownloads, color: 'bg-red-500' }, { name: 'Notes', count: stats.notesDownloads, color: 'bg-teal-500' }].map(item => <div key={item.name} className="space-y-2"><div className="flex justify-between text-sm"><span>{item.name}</span><span className="font-medium">{item.count}</span></div><div className="h-2 bg-muted rounded-full overflow-hidden"><div className={`h-full ${item.color} rounded-full`} style={{ width: `${Math.min((item.count / stats.totalDownloads) * 100, 100)}%` }} /></div></div>)}</div></Card><Card className="p-4 sm:p-6"><h2 className="text-lg font-semibold mb-4">Top Downloaded Files</h2><div className="space-y-3">{topDownloads.map((file, index) => <div key={file.id} className="flex items-center gap-3 p-3 bg-muted/50 rounded-lg"><div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center text-sm font-bold text-primary">{index + 1}</div><div className="flex-1 min-w-0"><p className="font-medium truncate">{file.title}</p><p className="text-xs text-muted-foreground">{file.category}</p></div><div className="flex items-center gap-1 text-sm text-muted-foreground"><Download className="h-4 w-4" />{file.download_count}</div></div>)}</div></Card><Card className="p-4 sm:p-6 md:col-span-2"><h2 className="text-lg font-semibold mb-4">Summary Statistics</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><div className="text-center p-4 bg-muted/50 rounded-lg"><p className="text-3xl font-bold text-primary">{files.length}</p><p className="text-sm text-muted-foreground">Total Files</p></div><div className="text-center p-4 bg-muted/50 rounded-lg"><p className="text-3xl font-bold text-green-600">{stats.totalDownloads}</p><p className="text-sm text-muted-foreground">Total Downloads</p></div><div className="text-center p-4 bg-muted/50 rounded-lg"><p className="text-3xl font-bold text-blue-600">{stats.totalVisitors.toLocaleString()}</p><p className="text-sm text-muted-foreground">Total Visitors</p></div><div className="text-center p-4 bg-muted/50 rounded-lg"><p className="text-3xl font-bold text-orange-600">{files.length > 0 ? Math.round(stats.totalDownloads / files.length) : 0}</p><p className="text-sm text-muted-foreground">Avg Downloads/File</p></div></div></Card></div></TabsContent>
        </Tabs>
      </div>
      <Dialog open={!!editFile} onOpenChange={() => setEditFile(null)}><DialogContent><DialogHeader><DialogTitle>Edit File</DialogTitle><DialogDescription>Update file information.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label htmlFor="edit-title">Title</Label><Input id="edit-title" value={editForm.title} onChange={(e) => setEditForm({ ...editForm, title: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="edit-description">Description</Label><Input id="edit-description" value={editForm.description} onChange={(e) => setEditForm({ ...editForm, description: e.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setEditFile(null)}>Cancel</Button><Button onClick={handleEdit}>Save Changes</Button></DialogFooter></DialogContent></Dialog>
      <AlertDialog open={!!deleteFile} onOpenChange={() => setDeleteFile(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete File</AlertDialogTitle><AlertDialogDescription>Are you sure you want to delete "{deleteFile?.title}"?</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={handleDelete} className="bg-destructive text-destructive-foreground">Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    </div>
  );
};

export default Admin;
